# render.yamlです！
version: 1
services:
  - type: web
    name: rarirurero-wakame
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16
